import { Contact } from "@/types/ContactTypes";

const contact = new Contact({
	additional_attributes: {},
	availability_status: 'online',
	email: 'victor+linkbaseab@unikkod.se',
	id: 2,
	name: 'Linkbase AB',
	phone_number: null,
	identifier: 'fd678e9b-ca2e-48d4-84d7-85d81b69108d',
	thumbnail: '',
	custom_attributes: {
		company: 'Linkbase AB',
		organisation: '559259-0250',
		supabase_user_id: 'fd678e9b-ca2e-48d4-84d7-85d81b69108d',
	},
	last_activity_at: 1697196914,
	created_at: 1697151147,
	contactableInboxes: [],
	contact_inboxes: [
		{
			source_id: '43611b39-6f71-451a-a6ca-64b7137d8013',
			inbox: {
				id: 1,
				avatar_url: '',
				channel_id: 1,
				name: 'Linkbase',
				channel_type: 'Channel::WebWidget',
				greeting_enabled: false,
				greeting_message: '',
				working_hours_enabled: true,
				enable_email_collect: true,
				csat_survey_enabled: false,
				enable_auto_assignment: true,
				auto_assignment_config: {},
				out_of_office_message: '',
				working_hours: [
					{
						day_of_week: 0,
						closed_all_day: true,
						open_hour: null,
						open_minutes: null,
						close_hour: null,
						close_minutes: null,
						open_all_day: false,
					},
					{
						day_of_week: 1,
						closed_all_day: false,
						open_hour: 10,
						open_minutes: 0,
						close_hour: 16,
						close_minutes: 0,
						open_all_day: false,
					},
					{
						day_of_week: 2,
						closed_all_day: false,
						open_hour: 10,
						open_minutes: 0,
						close_hour: 16,
						close_minutes: 0,
						open_all_day: false,
					},
					{
						day_of_week: 3,
						closed_all_day: false,
						open_hour: 10,
						open_minutes: 0,
						close_hour: 16,
						close_minutes: 0,
						open_all_day: false,
					},
					{
						day_of_week: 4,
						closed_all_day: false,
						open_hour: 10,
						open_minutes: 0,
						close_hour: 16,
						close_minutes: 0,
						open_all_day: false,
					},
					{
						day_of_week: 5,
						closed_all_day: false,
						open_hour: 10,
						open_minutes: 0,
						close_hour: 16,
						close_minutes: 0,
						open_all_day: false,
					},
					{
						day_of_week: 6,
						closed_all_day: true,
						open_hour: null,
						open_minutes: null,
						close_hour: null,
						close_minutes: null,
						open_all_day: false,
					},
				],
				timezone: 'Europe/Stockholm',
				callback_webhook_url: null,
				allow_messages_after_resolved: true,
				lock_to_single_conversation: false,
				sender_name_type: 'friendly',
				business_name: null,
				widget_color: '#000000',
				website_url: 'linkbase.se',
				hmac_mandatory: false,
				welcome_title: '',
				welcome_tagline: '',
				web_widget_script:
					'\n    <script>\n      (function(d,t) {\n        var BASE_URL="https://linkbase-chat.up.railway.app";\n        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];\n        g.src=BASE_URL+"/packs/js/sdk.js";\n        g.defer = true;\n        g.async = true;\n        s.parentNode.insertBefore(g,s);\n        g.onload=function(){\n          window.chatwootSDK.run({\n            websiteToken: \'o7dSSuaBq6z8JiFeqkQgZLUU\',\n            baseUrl: BASE_URL\n          })\n        }\n      })(document,"script");\n    </script>\n    ',
				website_token: 'o7dSSuaBq6z8JiFeqkQgZLUU',
				selected_feature_flags: [
					'attachments',
					'emoji_picker',
					'end_conversation',
				],
				reply_time: 'in_a_few_minutes',
				hmac_token: 'HUSs3r2ePTAFsP8ztGvjYnEo',
				pre_chat_form_enabled: true,
				pre_chat_form_options: {
					pre_chat_fields: [
						{
							name: 'fullName',
							type: 'text',
							label: 'Name',
							enabled: true,
							required: true,
							field_type: 'standard',
							placeholder: 'Enter name',
						},
						{
							name: 'emailAddress',
							type: 'email',
							label: 'Email',
							enabled: false,
							required: false,
							field_type: 'standard',
							placeholder: 'Ange email',
						},
						{
							name: 'phoneNumber',
							type: 'text',
							label: 'Phone number',
							enabled: false,
							required: false,
							field_type: 'standard',
							placeholder: 'phoneNumber',
						},
						{
							name: 'supabase_user_id',
							type: 'text',
							label: 'Supabase User ID',
							values: [],
							enabled: false,
							required: false,
							field_type: 'contact_attribute',
							placeholder: 'Supabase User ID',
						},
						{
							name: 'company',
							type: 'text',
							label: 'Company',
							values: [],
							enabled: false,
							required: false,
							field_type: 'contact_attribute',
							placeholder: 'Company',
						},
						{
							name: 'organisation',
							type: 'text',
							label: 'Organisation',
							values: [],
							enabled: false,
							required: false,
							field_type: 'contact_attribute',
							placeholder: 'Organisation',
						},
					],
					pre_chat_message: '',
				},
				continuity_via_email: true,
				messaging_service_sid: null,
				phone_number: null,
				provider: null,
			},
		},
	],
});

export { contact };
